# Generated by Django 4.2.2 on 2023-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="userprofile/download.png", upload_to="userprofile"
            ),
        ),
    ]
